export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const titles: Record<string,string> = { ar: "Privacy", en: "Privacy" };
  return { title: titles[locale] ?? titles.en, alternates: { canonical: absoluteUrl(`/${locale}/privacy`), languages: { en: absoluteUrl("/en/privacy"), ar: absoluteUrl("/ar/privacy") } } };
}

import { setRequestLocale } from "next-intl/server";
import type { Metadata } from "next";
import { absoluteUrl } from "@/lib/seo";
import { ArrowUpRight, Database, Eye, Lock, ShieldCheck } from "lucide-react";
export default async function PrivacyPage({ params }: { params: Promise<{ locale: string }> }){const { locale } = await params; setRequestLocale(locale); const ar=locale==="ar";const cards=[["ما البيانات التي نتعامل معها؟","What information do we handle?","بيانات الحساب وطلبات الاستفسار والحجز وبعض السجلات التقنية اللازمة لتشغيل المنصة.","Account data, inquiry and booking requests, and technical records needed to operate the platform.",Database],["كيف نستخدمها؟","How is it used?","لتقديم الخدمات وتشغيل الحسابات ومعالجة الطلبات وتحسين التجربة.","To provide services, operate accounts, process requests, and improve the experience.",Eye],["هل نبيع بياناتك؟","Do we sell your data?","لا نبيع البيانات الشخصية.","We do not sell personal data.",Lock],["حقوقك","Your rights","يمكنك طلب الوصول إلى بياناتك أو حذفها عبر التواصل معنا.","You can request access to or deletion of your data by contacting us.",ShieldCheck]];return <main><section className="relative isolate overflow-hidden bg-[hsl(var(--primary-950))]"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=2200&q=85" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-black/70"/><div className="mx-auto flex min-h-[430px] max-w-7xl items-end px-4 pb-20 pt-32 sm:px-6 lg:px-8"><div className="max-w-3xl text-white"><p className="text-xs font-semibold uppercase tracking-[.28em] text-white/60">Aqarco / {ar?"الخصوصية":"PRIVACY"}</p><h1 className="mt-5 text-4xl font-semibold sm:text-5xl lg:text-6xl">{ar?"خصوصيتك مهمة.":"Your privacy matters."}</h1><p className="mt-5 text-lg leading-8 text-white/70">{ar?"توضيح بسيط لكيفية التعامل مع معلوماتك.":"A clear overview of how we handle your information."}</p></div></div></section><section className="relative z-10 mx-auto -mt-10 max-w-7xl px-4 pb-24 sm:px-6 lg:px-8"><div className="grid gap-5 md:grid-cols-2">{cards.map(([a,b,c,d,Icon])=>{const I=Icon as typeof Database;return <article key={b as string} className="rounded-3xl border bg-card p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[hsl(var(--primary-100))] text-[hsl(var(--primary-600))]"><I className="h-5 w-5"/></div><h2 className="mt-6 text-xl font-semibold">{ar?a:b}</h2><p className="mt-3 leading-7 text-muted-foreground">{ar?c:d}</p></article>})}</div></section><section className="bg-muted/40 py-20 text-center"><h2 className="text-3xl font-semibold">{ar?"وضوح أكبر، ثقة أكبر.":"More clarity. More trust."}</h2><a href={"/"+locale+"/contact"} className="mt-6 inline-flex items-center gap-2 font-semibold text-[hsl(var(--primary-600))]">{ar?"تواصل معنا":"Contact us"}<ArrowUpRight className="h-4 w-4"/></a></section></main>}
